### ISSUE TITLE
Allow alphanumeric section "numbers"

### ISSUE THREAD

**Issue by tranquility-base** [cloudcoderdotorg/CloudCoder#76]
Please allow alphanumeric section "numbers".

Our school uses alphanumeric section identifiers, but attempting to create a course with section, for example, of "T1" results in:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.cloudcoder.jetty.NestedJarClassLoader.runMain(Unknown Source)
    at org.cloudcoder.jetty.WebServer.runAdminCommand(Unknown Source)
    at org.cloudcoder.jetty.WebServer.handleCommand(Unknown Source)
    at org.cloudcoder.webserver.CloudCoderWebServer.main(CloudCoderWebServer.java:61)
Caused by: java.lang.NumberFormatException: For input string: "T1"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:481)
    at java.lang.Integer.parseInt(Integer.java:514)
    at org.cloudcoder.app.server.persist.util.ConfigurationUtil.askInt(ConfigurationUtil.java:71)
    at org.cloudcoder.app.server.persist.CreateCourse.main(CreateCourse.java:78)
    ... 8 more
```

**Comment by daveho** [comment]
Just thinking aloud: we would need to have a database refactoring that would allow an integer column to be converted to varchar.  I'm guessing this is probably doable.
