### ISSUE TITLE
Database error when registering students

### ISSUE THREAD

**Issue by kpjaskie** [cloudcoderdotorg/CloudCoder#79]
I've been trying to register a test student.  My install is done and seems to work properly but I wanted to look at it from a student's perspective before my semester starts.  My studentID file has only one line (with tabs between each field):
test	firstName	lastName	kpjaskie@gmail.com	password	1 

I keep getting the following error when trying to register this test student:

java.lang.IllegalArgumentException: Unsupported conversion from java.lang.Integer to java.lang.String
        at org.cloudcoder.app.server.persist.util.DBUtil.convertValue(DBUtil.java:820)
        at org.cloudcoder.app.server.persist.util.DBUtil.loadModelObjectFields(DBUtil.java:926)
        at org.cloudcoder.app.server.persist.util.DBUtil.loadModelObjectFields(DBUtil.java:908)
        at org.cloudcoder.app.server.persist.util.ConfigurationUtil.getUsersInCourse(ConfigurationUtil.java:455)
        at org.cloudcoder.app.server.persist.util.ConfigurationUtil.registerStudentsForCourseId2(ConfigurationUtil.java:391)
        at org.cloudcoder.app.server.persist.RegisterStudents.registerStudents(RegisterStudents.java:49)
        at org.cloudcoder.app.server.persist.RegisterStudents.main(RegisterStudents.java:18)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.cloudcoder.jetty.NestedJarClassLoader.runMain(NestedJarClassLoader.java:107)
        at org.cloudcoder.jetty.WebServer.runAdminCommand(WebServer.java:99)
        at org.cloudcoder.jetty.WebServer.handleCommand(WebServer.java:86)
        at org.cloudcoder.webserver.CloudCoderWebServer.main(CloudCoderWebServer.java:61)
Database error: Unsupported conversion from java.lang.Integer to java.lang.String

Not sure what to do next.  Any ideas?

**Comment by daveho** [comment]
This should be fixed, closing.
